apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: asset-testing-ui-deployment
  name: asset-testing-ui-deployment
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: asset-testing-ui-deployment
  type: NodePort
status:
  loadBalancer: {}
